// 256 short, common, distinct English words that are easy to say and hear on a phone call.
export const WORDS = [
  'apple', 'anchor', 'arrow', 'autumn', 'baby', 'badge', 'bakery', 'balloon',
  'bamboo', 'banana', 'basket', 'beach', 'bicycle', 'blanket', 'bottle', 'bridge',
  'bucket', 'butter', 'button', 'cabbage', 'camel', 'camera', 'candle', 'canoe',
  'carpet', 'carrot', 'castle', 'cherry', 'chicken', 'circle', 'cobra', 'coconut',
  'coffee', 'comet', 'cookie', 'copper', 'cotton', 'cowboy', 'crayon', 'cricket',
  'crystal', 'cupboard', 'curtain', 'cushion', 'dancer', 'desert', 'diamond', 'dinner',
  'doctor', 'dolphin', 'donkey', 'dragon', 'drum', 'eagle', 'elbow', 'elephant',
  'engine', 'falcon', 'farmer', 'feather', 'festival', 'finger', 'flower', 'forest',
  'fountain', 'frog', 'garden', 'garlic', 'giant', 'ginger', 'giraffe', 'glove',
  'goat', 'golden', 'gorilla', 'grape', 'guitar', 'hammer', 'harbour', 'helmet',
  'hippo', 'honey', 'horse', 'hotel', 'iceberg', 'igloo', 'island', 'jacket',
  'jaguar', 'jasmine', 'jelly', 'jungle', 'kettle', 'kitchen', 'kitten', 'koala',
  'ladder', 'lantern', 'lemon', 'leopard', 'library', 'lily', 'lion', 'lizard',
  'lobster', 'lotus', 'magnet', 'mango', 'marble', 'meadow', 'melon', 'mirror',
  'monkey', 'morning', 'mountain', 'muffin', 'museum', 'needle', 'noodle', 'number',
  'ocean', 'octopus', 'olive', 'onion', 'orange', 'orchid', 'oven', 'owl',
  'paddle', 'palace', 'panda', 'paper', 'parrot', 'peacock', 'peanut', 'pebble',
  'pencil', 'penguin', 'pepper', 'piano', 'pickle', 'pillow', 'pirate', 'planet',
  'pocket', 'potato', 'pumpkin', 'puppet', 'puzzle', 'rabbit', 'radio', 'rainbow',
  'river', 'robot', 'rocket', 'saddle', 'sailor', 'salmon', 'sandal', 'scooter',
  'shadow', 'sheep', 'shovel', 'silver', 'singer', 'skate', 'snail', 'soccer',
  'spider', 'spinach', 'sponge', 'spoon', 'squirrel', 'station', 'sugar', 'summer',
  'sunset', 'sweater', 'table', 'tailor', 'teapot', 'temple', 'tennis', 'thunder',
  'tiger', 'toast', 'tomato', 'tractor', 'train', 'treasure', 'trumpet', 'tulip',
  'turtle', 'umbrella', 'unicorn', 'valley', 'van', 'velvet', 'violin', 'volcano',
  'wagon', 'walnut', 'water', 'whale', 'window', 'winter', 'wizard', 'wolf',
  'yogurt', 'zebra', 'acorn', 'airport', 'almond', 'apron', 'basil', 'beetle',
  'biscuit', 'blossom', 'buffalo', 'cactus', 'canyon', 'cereal', 'chalk', 'cheetah',
  'cinema', 'clover', 'parcel', 'compass', 'cupcake', 'daisy', 'dentist', 'domino',
  'dumpling', 'feast', 'ferry', 'firefly', 'football', 'forklift', 'gazelle', 'kite',
  'hamster', 'hedgehog', 'jigsaw', 'kayak', 'lettuce', 'llama', 'mushroom', 'napkin',
  'oyster', 'pancake', 'papaya', 'pelican', 'raccoon', 'reindeer', 'sandwich', 'yak',
];
